name: 'Telegram Message sender'
description: 'Send debug/failure/success messages through Telegram to you'
author: Binozo
branding:
  icon: 'send'  
  color: 'gray-dark'
inputs:
  telegram-bot-token:
    description: 'Telegram Bot Token'
    required: true
    default: ''
  telegram-user-id:
    description: 'Target Telegram User ID'
    required: true
    default: ''
  telegram-chat-id:
    description: 'Telegram Conversation ID between $telegram-user-id and the bot'
    required: false
    default: ''
  file-path:
    description: 'Path to the file you want so send'
    required: false
    default: ''
  message:
    description: 'Message to send'
    required: false
    default: 'GitHub Workflow completed'
runs:
  using: 'node16'
  main: 'index.js'