name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  telegram-bot-token:
    description: 'Telegram Bot Token'
    required: true
    default: ''
  telegram-user-id:
    description: 'Target Telegram User ID'
    required: true
    default: ''
  telegram-chat-id:
    description: 'Telegram Conversation ID between $telegram-user-id and the bot'
    required: false
    default: ''
  telegram-debug-chat:
    description: 'Telegram Conversation ID for debugging'
    required: false
    default: ''
  message:
    description: 'Message to send'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'index.js'