on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello world!
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        with:
          telegram-bot-token: ${{secrets.TELEGRAM_BOT_TOKEN}}
          telegram-user-id: ${{secrets.TELEGRAM_TARGET_USER_ID}}
          telegram-debug-chat: ${{secrets.TELEGRAM_DEBUG_CHAT}}
          message: "Hello World!"