name: test-workflow.yml
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Telegram Message sender
        uses: Binozo/TelegramNotifier@v1.6
        with:
          telegram-bot-token: ${{secrets.TELEGRAM_BOT_TOKEN}}
          telegram-chat-id: ${{secrets.TELEGRAM_TARGET_USER_ID}}
          message: "Hello World 💪"